---

- name: install VM
  hosts: vm_host
  remote_user: root

  roles:
    - install-vm

- name: install manageiq
  hosts: manageiq-vm  
  remote_user: vagrant
  #connection: local

  roles:
    - install-manageiq