
---
- expect:
    command: sudo passwd postgres
    responses:
      (?i)password: "smartvm"
    

# ↑ will ask to choose a password
- name: init postgresql db
  shell: >
   /usr/pgsql-9.4/bin/postgresql94-setup initdb;
  register: db_init_result
  failed_when: (db_init_result.stderr!="" and "Data directory is not empty" not in db_init_result.stderr)
  become: yes
  become_user: root

- name: configure postgresql db
  shell: >
   grep -q '^local\s' /var/lib/pgsql/9.4/data/pg_hba.conf || echo "local all all trust" | sudo tee -a /var/lib/pgsql/9.4/data/pg_hba.conf;
   sed -i.bak 's/\(^local\s*\w*\s*\w*\s*\)\(peer$\)/\1trust/' /var/lib/pgsql/9.4/data/pg_hba.conf;
   systemctl start postgresql-9.4;
   systemctl enable postgresql-9.4;
   su postgres -c "psql -c \"DROP ROLE IF EXISTS root\""
  become: yes
  become_user: root  

- name: create postgresql role root
  shell: su postgres -c "psql -c \"CREATE ROLE root SUPERUSER LOGIN PASSWORD 'smartvm'\"";
  become: yes
  become_user: root
  
