---
- name: Install manageIQ from Github
  git: repo=https://github.com/Ladas/manageiq.git version=VNF_demo_updated dest={{ansible_env.HOME}}/manageiq


- name: Add Git config
  shell: >
   cd {{ansible_env.HOME}}/manageiq;
   git config user.name "Billy Everyteen";
   git config user.email "Billy@manageiq-devel.com"   

- name: Add Git Upstream
  shell: >
   cd {{ansible_env.HOME}}/manageiq;
   git remote add upstream https://github.com/ManageIQ/manageiq.git
  register: git_upstream_result
  failed_when: (git_upstream_result.stderr!="" and "remote upstream already exists" not in git_upstream_result.stderr)

 
 
- name: rebase mnageIQ project
  shell: >
   git fetch upstream;
   git rebase -s recursive -X ours upstream/euwe;
   git pull -X theirs 
  args:
   chdir: "{{ansible_env.HOME}}/manageiq"

- name:  config bundle 
  shell: >
   source {{ansible_env.HOME}}/.rvm/scripts/rvm;
   bash -lc "bundle config build.pg --with-pg-config=/usr/pgsql-9.4/bin/pg_config"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name:  run bundler Install
  shell: >
    source {{ansible_env.HOME}}/.rvm/scripts/rvm;
    bash -lc "bundle install"
  args:
   chdir: "{{ansible_env.HOME}}/manageiq"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
  
- name:  run bundler update
  shell: >
    source {{ansible_env.HOME}}/.rvm/scripts/rvm;
    bash -lc "bundle update"
  args:
   chdir: "{{ansible_env.HOME}}/manageiq"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

- name: Run mnageIQ setup
  shell: >
   source {{ansible_env.HOME}}/.rvm/scripts/rvm;
   bash -lc "{{ansible_env.HOME}}/.rvm/rubies/ruby-{{ruby_version}}/bin/ruby bin/setup"
  args:
   chdir: "{{ansible_env.HOME}}/manageiq"
  environment:
   PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"

#- name:  run bundler Update
#  command: bash -lc "cd {{ansible_env.HOME}}/manageiq && bundle update"

- name: start manageiq
  shell: >
   source {{ansible_env.HOME}}/.rvm/scripts/rvm;
   bash -lc "bundle exec rake evm:start" 
  args:
    chdir: "{{ansible_env.HOME}}/manageiq"
  environment:
    PATH: "{{ rvm_path }}:{{ ansible_env.PATH }}"
  #shell: >
   #bundle exec rake evm:start;





