---
- name: Install manageIQ from Github
  git: repo=https://github.com/Ladas/manageiq.git version=VNF_demo_updated dest=/home/vagrant/manageiq
  

- name:  run bundler Install
  shell: >
   cd /home/vagrant/manageiq;
   bundle install
  become_user: vagrant

- name: Run mnageIQ setup
  shell: >
   cd /home/vagrant/manageiq;
   git remote add upstream git@github.com:ManageIQ/manageiq.git;
   git fetch upstream;
   git rebase upstream/master;
   bin/setup

- name: start manageiq
  shell: >
   bundle exec rake evm:start;





