---
- name: Creates directory
  file: path=~/manageiq_vm state=directory

- name: downloading vagrant
  yum: name=https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.rpm state=present

- name: install libvirt dependency
  yum: name={{ item }} state=present
  with_items:
   - libvirt-devel
   - libxslt-devel
   - libxml2-devel
   - qemu-img
   - gcc
   - rsync

